version: '3.8'

services:
  # ----------------------------
  # BACKEND (Sanic API)
  # ----------------------------
  backend:
    build: ./backend
    container_name: campushub_backend
    volumes:
      - ./backend:/app  # Canlı kod güncellemesi (Hot Reload) için
    command: sanic src.server:app --host=0.0.0.0 --port=8000 --debug --auto-reload
    ports:
      - "8000:8000"
    environment:
      - DB_URL=mysql://hubuser:hubpass@db:3306/campushub
      - REDIS_URL=redis://cache:6379
      - SECRET_KEY=gizli_anahtar_buraya
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=uyanogluyusuf@gmail.com
      - SMTP_PASS=iklftblyhelhjtpo
 
    depends_on:
      - db
      - cache
    networks:
      - hub_network
    restart: unless-stopped

# ----------------------------
  # FRONTEND (React + Vite)
  # ----------------------------
  frontend:
    build: ./frontend
    container_name: campushub_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - hub_network

  # ----------------------------
  # VERİTABANI (MySQL 8)
  # ----------------------------
  db:
    image: mysql:8.0
    container_name: campushub_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: campushub
      MYSQL_USER: hubuser
      MYSQL_PASSWORD: hubpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - hub_network
    command: --default-authentication-plugin=mysql_native_password

  # ----------------------------
  # ÖNBELLEK (Redis - Cache)
  # ----------------------------
  cache:
    image: redis:7-alpine
    container_name: campushub_redis
    ports:
      - "6379:6379"
    networks:
      - hub_network

# Veritabanı verilerini kalıcı yap
volumes:
  db_data:

# Servisleri aynı ağda topla
networks:
  hub_network:
    driver: bridge
